const $=id=>document.getElementById(id);let user,business;const esc=x=>{let d=document.createElement("div");d.textContent=x??"";return d.innerHTML},msg=(id,x)=>$(id).textContent=x;
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
async function start(){let{data:{user:u}}=await sb.auth.getUser();if(!u)return location="login.html";user=u;$("welcome").textContent="Welcome, "+(u.user_metadata?.name||u.email);await loadBusiness();await loadProducts();await loadServices();await loadRequests()}
async function loadBusiness(){let{data,error}=await sb.from("businesses").select("*").eq("owner_id",user.id).maybeSingle();if(error)return msg("businessMsg","❌ "+error.message);business=data;if(!data)return;["name","slug","tagline","phone","address","logo_url"].forEach(k=>$("b"+(k==="name"?"name":k==="slug"?"slug":k==="tagline"?"tagline":k==="phone"?"phone":k==="address"?"address":"logo")).value=data[k]||"");let url="site.html?slug="+encodeURIComponent(data.slug);$("publicLink").textContent=url;$("openPublic").href=url;$("openPublic").classList.remove("hidden")}
$("saveBusiness").onclick=async()=>{let name=$("bname").value.trim(),slug=$("bslug").value.trim().toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-");if(!name||!slug)return msg("businessMsg","Name and slug required.");let p={owner_id:user.id,name,slug,tagline:$("btagline").value.trim(),phone:$("bphone").value.trim(),address:$("baddress").value.trim(),logo_url:$("blogo").value.trim()};let{error}=business?await sb.from("businesses").update(p).eq("id",business.id):await sb.from("businesses").insert(p);if(error)return msg("businessMsg","❌ "+error.message);msg("businessMsg","✅ Saved.");await loadBusiness();await loadProducts();await loadServices();await loadRequests()};
async function loadProducts(){if(!business)return $("productList").innerHTML="<p>Create business first.</p>";let{data,error}=await sb.from("products").select("*").eq("business_id",business.id).order("created_at",{ascending:false});if(error)return $("productList").innerHTML="❌ "+esc(error.message);$("productList").innerHTML=(data||[]).map(p=>`<div class="item"><div>${p.image_url?`<img class="product-img" src="${esc(p.image_url)}">`:""}<b>${esc(p.name)}</b><p>${esc(p.description||"")}</p>₹${esc(p.price||0)}</div><button class="btn red" onclick="delP('${p.id}')">Delete</button></div>`).join("")||"<p>No products.</p>"}
window.delP=async id=>{if(confirm("Delete product?")){let{error}=await sb.from("products").delete().eq("id",id);if(error)alert(error.message);loadProducts()}};
$("addProduct").onclick=async()=>{if(!business)return msg("productMsg","Create business first.");let name=$("pname").value.trim();if(!name)return msg("productMsg","Product name required.");let{error}=await sb.from("products").insert({business_id:business.id,name,price:Number($("pprice").value||0),description:$("pdesc").value.trim(),image_url:$("pimage").value.trim(),active:true});if(error)return msg("productMsg","❌ "+error.message);msg("productMsg","✅ Added.");loadProducts()};
async function loadServices(){if(!business)return $("serviceList").innerHTML="<p>Create business first.</p>";let{data,error}=await sb.from("services").select("*").eq("business_id",business.id).order("created_at",{ascending:false});if(error)return $("serviceList").innerHTML="❌ "+esc(error.message);$("serviceList").innerHTML=(data||[]).map(s=>`<div class="item"><div><b>${esc(s.name)}</b><p>${esc(s.description||"")}</p>₹${esc(s.price||0)}</div><button class="btn red" onclick="delS('${s.id}')">Delete</button></div>`).join("")||"<p>No services.</p>"}
window.delS=async id=>{if(confirm("Delete service?")){let{error}=await sb.from("services").delete().eq("id",id);if(error)alert(error.message);loadServices()}};
$("addService").onclick=async()=>{if(!business)return msg("serviceMsg","Create business first.");let name=$("sname").value.trim();if(!name)return msg("serviceMsg","Service name required.");let{error}=await sb.from("services").insert({business_id:business.id,name,price:Number($("sprice").value||0),description:$("sdesc").value.trim(),active:true});if(error)return msg("serviceMsg","❌ "+error.message);msg("serviceMsg","✅ Added.");loadServices()};
async function loadRequests(){if(!business)return $("requestList").innerHTML="<p>Create business first.</p>";let{data,error}=await sb.from("requests").select("*").eq("business_id",business.id).order("created_at",{ascending:false});if(error)return $("requestList").innerHTML="❌ "+esc(error.message);$("requestList").innerHTML=(data||[]).map(r=>`<div class="card"><span class="status ${esc(r.status||"pending")}">${esc((r.status||"pending").replaceAll("_"," "))}</span><h3>${r.type==="booking"?"📅 Booking":"🛒 Order"}: ${esc(r.item_name||"")}</h3><p>👤 ${esc(r.customer_name||"")}</p><p>📞 ${esc(r.customer_phone||"")}</p><p>💬 ${esc(r.note||"-")}</p><div class="actions">${["accepted","rejected","processing","out_for_delivery","delivered","completed"].map(s=>`<button class="btn light" onclick="status('${r.id}','${s}')">${s.replaceAll("_"," ")}</button>`).join("")}</div></div>`).join("")||"<p>No orders.</p>"}
window.status=async(id,status)=>{let{error}=await sb.from("requests").update({status}).eq("id",id);if(error)alert(error.message);loadRequests()};$("logout").onclick=async()=>{await sb.auth.signOut();location="index.html"};start();
