create extension if not exists pgcrypto;
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,role text default 'owner',is_blocked boolean default false,created_at timestamptz default now());
create table if not exists businesses(id uuid primary key default gen_random_uuid(),owner_id uuid references auth.users(id) on delete cascade,name text not null,slug text unique not null,category text,tagline text,phone text,whatsapp text,address text,about text,logo_url text,status text default 'Active',created_at timestamptz default now());
create table if not exists products(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,name text,price numeric,description text,image_url text,created_at timestamptz default now());
create table if not exists services(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,name text,price numeric,description text,image_url text,created_at timestamptz default now());
create table if not exists orders(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,customer_id uuid references auth.users(id),customer_name text,item_name text,amount numeric,status text default 'Pending',created_at timestamptz default now());
create table if not exists appointments(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,customer_id uuid references auth.users(id),customer_name text,service_name text,appointment_date date,appointment_time text,message text,status text default 'Pending',created_at timestamptz default now());
alter table profiles enable row level security;alter table businesses enable row level security;alter table products enable row level security;alter table services enable row level security;alter table orders enable row level security;alter table appointments enable row level security;
create policy "profile select" on profiles for select to authenticated using(id=auth.uid() or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "profile insert" on profiles for insert to authenticated with check(id=auth.uid());
create policy "profile update" on profiles for update to authenticated using(id=auth.uid() or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "business read" on businesses for select using(status='Active' or owner_id=auth.uid() or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "business write" on businesses for all to authenticated using(owner_id=auth.uid() or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin')) with check(owner_id=auth.uid());
create policy "products read" on products for select using(true);
create policy "products write" on products for all to authenticated using(exists(select 1 from businesses b where b.id=business_id and b.owner_id=auth.uid())) with check(exists(select 1 from businesses b where b.id=business_id and b.owner_id=auth.uid()));
create policy "services read" on services for select using(true);
create policy "services write" on services for all to authenticated using(exists(select 1 from businesses b where b.id=business_id and b.owner_id=auth.uid())) with check(exists(select 1 from businesses b where b.id=business_id and b.owner_id=auth.uid()));
create policy "orders insert" on orders for insert to authenticated with check(customer_id=auth.uid());
create policy "orders read" on orders for select to authenticated using(customer_id=auth.uid() or exists(select 1 from businesses b where b.id=business_id and b.owner_id=auth.uid()) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "appointments insert" on appointments for insert to authenticated with check(customer_id=auth.uid());
create policy "appointments read" on appointments for select to authenticated using(customer_id=auth.uid() or exists(select 1 from businesses b where b.id=business_id and b.owner_id=auth.uid()) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
insert into storage.buckets(id,name,public) values('business-media','business-media',true) on conflict(id) do nothing;
create policy "media public" on storage.objects for select using(bucket_id='business-media');
create policy "media upload" on storage.objects for insert to authenticated with check(bucket_id='business-media');
create policy "media delete" on storage.objects for delete to authenticated using(bucket_id='business-media');
-- After creating your admin account: update profiles set role='admin' where id=(select id from auth.users where email='YOUR_ADMIN_EMAIL');
